controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 30
    base_frame_id: base_link

    left_wheel_names: ["fl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint"]
    wheel_separation: 0.5
    wheel_radius: 0.05

    use_stamped_vel: false

# joint_controller: